version: '3.7'

services:
  cht-user-management:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EXTERNAL_PORT=${EXTERNAL_PORT:-3000}
      - COOKIE_PRIVATE_KEY=${COOKIE_PRIVATE_KEY}
      - CONFIG_NAME=${CONFIG_NAME}
    container_name: cht-user-management
    ports:
      - '${EXTERNAL_PORT}:${PORT:-3000}'
    restart: always
    command: npm start
