services:
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-data:/data
    network_mode: host
    

  cht-user-management:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EXTERNAL_PORT=${EXTERNAL_PORT:-3000}
      - COOKIE_PRIVATE_KEY=${COOKIE_PRIVATE_KEY}
      - CONFIG_NAME=${CONFIG_NAME}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - QUEUE_PRIVATE_KEY=${QUEUE_PRIVATE_KEY}
    ports:
      - '${EXTERNAL_PORT-3000}:${PORT:-3000}'
    restart: always
    command: npm start
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    command: npm run start:worker
    network_mode: host
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - QUEUE_PRIVATE_KEY=${QUEUE_PRIVATE_KEY}
    depends_on:
      - redis

volumes:
  redis-data:
