FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV production

COPY package*.json .
RUN apk add git
RUN npm ci --omit=dev

COPY src ./src
COPY tsconfig.json .
RUN npm run build

CMD npm run start:worker
