export default [
  ["Laikipia West", "KINAMBA", "Joyce Waruguru Macharia", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Nancy Wamuyu Maina", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "KINAMBA", "Mary Gachambi Kanyugo", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Francis Kariithi Maina", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Keziah Muthoni Mwangi", "Laikipia West", "KINAMBA E"],
  ["Laikipia West", "KINAMBA", "Agnes Nyambura Munene", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Nicholas Ndiritu Kigano", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "KINAMBA", "Juster Churi Murage", "Laikipia West", "NJORUA"],
  ["Laikipia West", "KINAMBA", "Mary Wagaki Maina", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Richard Kanyi kibuthu", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Lucy Nyambura Waitiki", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Esther Njeri Tangira", "Laikipia West", "KINAMBA E"],
  ["Laikipia West", "KINAMBA", "Margaret Wanjiru Mbau", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Eunice Wanjiru Macharia", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "KINAMBA", "Jecinta Wanjiku Kamau", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Joseph Mutahi Thiuri", "Laikipia West", "KINAMBA D"],
  ["Laikipia West", "KINAMBA", "Martha Maina Wambui", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Josephat Munanu Rukwaro", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "John Mugera Rukwaro", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Geoffrey Wanyoike Makumi", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "KINAMBA", "Jane Wanjiru Kiruri", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Lucy Wambui Gichuki", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "KINAMBA", "Cypriano Kaberia Narangui", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Grace Wanjiru Thuita", "Laikipia West", "KINAMBA D"],
  ["Laikipia West", "KINAMBA", "Virginia Njeri Njuguna", "Laikipia West", "KINAMBA D"],
  ["Laikipia West", "KINAMBA", "Zachary Nderitu Njagi", "Laikipia West", "KINAMBA E"],
  ["Laikipia West", "KINAMBA", "Esther Nyambura Muchiri", "Laikipia West", "KINAMBA D"],
  ["Laikipia West", "KINAMBA", "James Gitonga Muriithi", "Laikipia West", "KINAMBA E"],
  ["Laikipia West", "KINAMBA", "Francis Nderitu Munanu", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Rose Wairimu Gaturuku", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Penina Waithira", "Laikipia West", "KINAMBA C"],
  ["Laikipia West", "KINAMBA", "Monicah Wanjiru Mwangi", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "KINAMBA", "Moses Mungai Nganga", "Laikipia West", "KINAMBA E"],
  ["Laikipia West", "KINAMBA", "Grace Wangui Gikaria", "Laikipia West", "KINAMBA E"],
  ["Laikipia West", "KINAMBA", " Wilson   Chirchir Chepotip", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "KINAMBA", "Silas Ndumia Wagura", "Laikipia West", "NJORUA B"],
  ["Laikipia West", "KINAMBA", "Agnes Njeri wanjiru", "Laikipia West", "NJORUA"],
  ["Laikipia West", "NJORUA", "Hannah Waruguru Kiragu", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "NJORUA", "Milicent Kusimba Ngonde", "Laikipia West", "KINAMBA D"],
  ["Laikipia West", "NJORUA", "Joseph Kagika Kibunja", "Laikipia West", "NJORUA"],
  ["Laikipia West", "NJORUA", "Milka Wambui Kamau", "Laikipia West", "NJORUA B"],
  ["Laikipia West", "NJORUA", "Jacqueline Wamuyu Wanjiku", "Laikipia West", "NJORUA B"],
  ["Laikipia West", "NJORUA", "Simon Kihara Njeri", "Laikipia West", "NJORUA"],
  ["Laikipia West", "NJORUA", "Joyce Gathoni Mucheru", "Laikipia West", "NJORUA B"],
  ["Laikipia West", "NJORUA", "Ann Mwihaki Mugo", "Laikipia West", "KINAMBA"],
  ["Laikipia West", "NJORUA", "Joseph Mwangi Maina", "Laikipia West", "NJORUA"],
  ["Laikipia West", "NJORUA", "David Muraya Mwangi", "Laikipia West", "NJORUA B"],
  ["Laikipia West", "NJORUA", "Beatrice Wairimu Njuguna", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "NJORUA", "Anna  Wanjiru Muriithi", "Laikipia West", "NJORUA B"],
  ["Laikipia West", "NJORUA", "Teresah  Nyawira Kinyanjui", "Laikipia West", "KINAMBA B"],
  ["Laikipia West", "NJORUA", "Paul Mwathi John", "Laikipia West", "NJORUA"],
  ["Laikipia West", "MATUIKU", "David  Wambugu", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "MATUIKU", "Annah  Njeri", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "MATUIKU", "Harrison Kiarie Nganga", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "MWENJE", "James  Kahora", "Laikipia West", "Matuiku"],
  ["Laikipia West", "MWENJE", "Alice  Wanja Kamau", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "MWENJE", "Duncan  Kuria", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "MWENJE", "Mary  Njeri", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "MWENJE", "Joel Wamae Waithaka", "Laikipia West", "Karumaindo"],
  ["Laikipia West", "SALAMA", "Jane Wangechi Kabukuru", "Laikipia West", "MURUKU"],
  ["Laikipia West", "SALAMA", "John Biwot Kipkuargat ", "Laikipia West", "LORIEN"],
  ["Laikipia West", "SALAMA", "Benson   MisoiI Kipkemboi", "Laikipia West", "LORIEN"],
  ["Laikipia West", "SALAMA", "Daniel Meli Kipyego", "Laikipia West", "LORIEN"],
  ["Laikipia West", "SALAMA", "Jane Kibet Cherono", "Laikipia West", "LORIEN"],
  ["Laikipia West", "SALAMA", "George Kanyi Gitonga", "Laikipia West", "MURUKU"],
  ["Laikipia West", "SALAMA", "Joseph Kimeto Kataam ", "Laikipia West", "LORIEN"],
  ["Laikipia West", "SALAMA", "Salome Wambui gitau", "Laikipia West", "MURUKU"],
  ["Laikipia West", "SALAMA", "Robert Meiponyi Kipkorir", "Laikipia West", "MURUKU"],
  ["Laikipia West", "SALAMA", "Hannah  Wambui", "Laikipia West", "MURUKU"],
  ["Laikipia West", "SALAMA", "Francis Mwaura ", "Laikipia West", "MURUKU"],
  ["Laikipia West", "KARABA", "NANCY HESUON AKUTA", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "ANDREW WANJOHI MWANGI", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "BEUTAH KAMINDO MURIITHI", "Laikipia West", "KARABA C"],
  ["Laikipia West", "KARABA", "Margaret WAHOME WANJUGU", "Laikipia West", "KARABA C"],
  ["Laikipia West", "KARABA", "JOHN KARIUKI KAMUNYA", "Laikipia West", "KARABA C"],
  ["Laikipia West", "KARABA", "Jacinta GICHUKI Wambui", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "GRACE WANGECI NDERITU", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "ANDREW WANJOHI GITHU", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "SAMWEL CHEMUNA KIPSERECH", "Laikipia West", "karaba"],
  ["Laikipia West", "KARABA", "LUCY MUTHONI KINGORI", "Laikipia West", "karaba"],
  ["Laikipia West", "KARABA", "CATHERINE WAIRIMU", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "CATHERINE SIMOI DIKIRR", "Laikipia West", "karaba"],
  ["Laikipia West", "KARABA", "RICHARD KIPRONO", "Laikipia West", "karaba"],
  ["Laikipia West", "KARABA", "JOHN MATHENGE Wothaya", "Laikipia West", "karaba"],
  ["Laikipia West", "KARABA", "ESTHER WANJIRU", "Laikipia West", "KARABA B"],
  ["Laikipia West", "KARABA", "HANNA WANGARI", "Laikipia West", "KARABA C"],
  ["Laikipia West", "MUHOTETU", "Nicholas Kiprono Maswai", "Laikipia West", "MUHOTETU C ( CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Sammy Wangai Karimi", "Laikipia West", "MUHOTETU C ( CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Lucy Wangari Gachugi", "Laikipia West", "MUHOTETU A ( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "Mary Wanjiku Maina", "Laikipia West", "MUHOTETU A ( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "Leah Njoki Chege", "Laikipia West", "MUHOTETU B ( GATAMI)"],
  ["Laikipia West", "MUHOTETU", "Joseph Mutua Muthoni", "Laikipia West", "MUHOTETU A ( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "Beth Wanja Kariuki", "Laikipia West", "MUHOTETU C ( CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Rahab Muthoni Wachira", "Laikipia West", "MUHOTETU B( GATAMI)"],
  ["Laikipia West", "MUHOTETU", "Susan Waithera Gitahi", "Laikipia West", "MUHOTETU A( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "Ann Nyokabi Muchiri", "Laikipia West", "MUHOTETU A( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "John Kamau Gachau", "Laikipia West", "MUHOTETUB(GATAMI)"],
  ["Laikipia West", "MUHOTETU", "John Ndungu Maina", "Laikipia West", "MUHOTETU A( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "Elizabeth Wangu Kamau", "Laikipia West", "MUHOTETU A( MANJANI)"],
  ["Laikipia West", "MUHOTETU", "Ignatius Ngaara Wachania", "Laikipia West", "MUHOTETU B( GATAMI)"],
  ["Laikipia West", "MUHOTETU", "Jane Waithera Njuguna", "Laikipia West", "MUHOTETU B( GATAMI)"],
  ["Laikipia West", "MUHOTETU", "Eva Wambui Njoki", "Laikipia West", "MUHOTETU B( GATAMI)"],
  ["Laikipia West", "MUHOTETU", "Jelevasio Makumi Kingori", "Laikipia West", "MUHOTETU B(GATAMI)"],
  ["Laikipia West", "MUHOTETU", "Margaret Wangari Nyambura", "Laikipia West", "MUHOTETU C(CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Jackquiline Mbatha Musyoki", "Laikipia West", "MUHOTETU C(CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Beatrice Wanjiru Wangai", "Laikipia West", "MUHOTETU C(CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Virginia Mugure Murioga", "Laikipia West", "MUHOTETU C(CHUNGUTI)"],
  ["Laikipia West", "MUHOTETU", "Stella Chebet Barno", "Laikipia West", "MUHOTETU A(MANJANI)"],
  ["Laikipia West", "MELWA", "Duncan Wanjohi Mwangi", "Laikipia West", "Njoguini"],
  ["Laikipia West", "MELWA", "Wilson Ndungu Wanjuki", "Laikipia West", "Njoguini"],
  ["Laikipia West", "MELWA", "JOSPHAT MUTURA  GAKURU", "Laikipia West", "Njoguini"],
  ["Laikipia West", "MELWA", "ALICE  TABITHA  WAMBUI", "Laikipia West", "Njoguini"],
  ["Laikipia West", "MELWA", "EDITH  WANGUI  MUIRU", "Laikipia West", "Njoguini"],
  ["Laikipia West", "MELWA", "RUTH WANJIRU MACHARIA", "Laikipia West", "Njoguini"],
  ["Laikipia West", "LOSOGWA", "Peter Kinuthia Kibata", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Charles Wangondu Wachira", "Laikipia West", "SHAMANEI"],
  ["Laikipia West", "LOSOGWA", "Margret Wahiga Gitonga", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "LOSOGWA", "Esther Nyambura Kibui", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "LOSOGWA", "Jane Wanjiru Wanjohi", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "LOSOGWA", "Daniel Njuguna Karumbi", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "LOSOGWA", "Emma Wacu Njenga", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Jecinta Nyambura Njun'ge", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Samuel Mugo Irungu", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Susan Wanjiru Ruga", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Agnes Njeri", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Keziah Njoroge", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "LOSOGWA", "Milliam Wachuka", "Laikipia West", "LOSOGWA"],
  ["Laikipia West", "SHAMANEI", "Lucy Njoki Wambugu", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "SHAMANEI", "Nancy  wangari Muchiri", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "SHAMANEI", "Fredrick Wachira Maina", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "SHAMANEI", "Mary Wangui Gichuhi", "Laikipia West", "LOSOGWA B"],
  ["Laikipia West", "Mahianyu", "Beatrice Kimuhu Mwihaki", "Laikipia West", "Mahianyu"],
  ["Laikipia West", "Mahianyu", "Hannah Mugo Wanjiru", "Laikipia West", "Mahianyu"],
  ["Laikipia West", "Mahianyu", "Michael Kamotho Chege", "Laikipia West", "Mahianyu"],
  ["Laikipia West", "Mahianyu", "Mary Mwangi Nyambura", "Laikipia West", "Mahianyu B"],
  ["Laikipia West", "Mahianyu", "Joyce Chege Nyawira", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "Michael Ndegwa Ndahi", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "Peter Mwithukia Kiniu", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "Naomi Maina Wambui", "Laikipia West", "Mahianyu B"],
  ["Laikipia West", "Mahianyu", "Joyce Kanuria Wanjira", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "GRACE MUTHONI GITHINJI", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "DAMARIS WANGECHI NJUGUNA", "Laikipia West", "Mahianyu"],
  ["Laikipia West", "Mahianyu", "MARGARET WANJIRU NDIRANGU", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "EUNICE WANJUGU KIBUI", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "MAGDALENE WARUGURU MUTUIKE", "Laikipia West", "Kiandege"],
  ["Laikipia West", "Mahianyu", "ANN WANJIKU MWANGI", "Laikipia West", "Mahianyu B"],
  ["Laikipia West", "Mahianyu", "CHARLES WACHIRA WANGUI", "Laikipia West", "Kiandege"],
  ["Laikipia West", "MAINA", "Margaret Wangui Kihungu", "Laikipia West", "Kiandege"],
  ["Laikipia West", "MAINA", "Joyce Gathoni Mwaniki", "Laikipia West", "MAINA F"],
  ["Laikipia West", "MAINA", "Terry Wanjiru Mwaniki", "Laikipia West", "MAINA C"],
  ["Laikipia West", "MAINA", "Purity Wangui Mwendia", "Laikipia West", "MAINA F"],
  ["Laikipia West", "MAINA", "Ann Nyambura Kinyua", "Laikipia West", "MAINA F"],
  ["Laikipia West", "MAINA", "Jecinta Wanjiku Kahwai", "Laikipia West", "MAINA"],
  ["Laikipia West", "MAINA", "David Litiamasu Limbasoni", "Laikipia West", "MAINA D"],
  ["Laikipia West", "MAINA", "Mary Wangare Kimani", "Laikipia West", "MAINA"],
  ["Laikipia West", "MAINA", "Serah Wambui Ndirangu", "Laikipia West", "MAINA E"],
  ["Laikipia West", "MAINA", "Simon Nganga Nganga", "Laikipia West", "MAINA C"],
  ["Laikipia West", "MAINA", "Margaret Wangare Kiburu", "Laikipia West", "MAINA C"],
  ["Laikipia West", "MAINA", "Samwel Kabage Kingori", "Laikipia West", "MAINA F"],
  ["Laikipia West", "MAINA", "Linah Nyokabi Mwangi", "Laikipia West", "MAINA B"],
  ["Laikipia West", "MAINA", "Lisper Muthoni Mwangi", "Laikipia West", "MAINA"],
  ["Laikipia West", "MAINA", "Jackline Riruka Aviasa", "Laikipia West", "MAINA F"],
  ["Laikipia West", "MAINA", "Veronicah Nyambura Mwangi", "Laikipia West", "MAINA B"],
  ["Laikipia West", "MAINA", "Hellen Mwende Mumo", "Laikipia West", "MAINA F"],
  ["Laikipia West", "MAINA", "Elizabeth Njeri Mwangi", "Laikipia West", "MAINA B"],
  ["Laikipia West", "MAINA", "Tabitha Njambi Wambui ", "Laikipia West", "MAINA C"],
  ["Laikipia West", "MAINA", "Martha Kawira Kamwara", "Laikipia West", "MAINA D"],
  ["Laikipia West", "MAINA", "Monicah Nduta Gicheha", "Laikipia West", "MAINA D"],
  ["Laikipia West", "MAINA", "Rahab Mumbi Muiruri", "Laikipia West", "MAINA E"],
  ["Laikipia West", "MAINA", "Emily Kemisa Anyako", "Laikipia West", "MAINA E"],
  ["Laikipia West", "MAINA", "Irene Waithera Waruru", "Laikipia West", "MAINA"],
  ["Laikipia West", "MAINA", "Elizepa Amwayi Mwimali", "Laikipia West", "MAINA F"],
  ["Laikipia West", "Uasonarock", "Grace Alimlim Ekiru", "Laikipia West", "KAICHAKUNI"],
  ["Laikipia West", "Uasonarock", " Jackson Kiloku  Moire", "Laikipia West", "KAICHAKUNI"],
  ["Laikipia West", "Uasonarock", "Cecilia Miniyo Lobenyo", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "Uasonarock", "Gladys Nyambura Wandimi", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "Uasonarock", "Rebecca Rukunja Endungu", "Laikipia West", "KAICHAKUNI"],
  ["Laikipia West", "Uasonarock", "Christopher Kiptoo Tanui", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "Uasonarock", "Esther Amukei Alepet", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "Uasonarock", "Monicah Muthungu Ekai", "Laikipia West", "KAICHAKUNI"],
  ["Laikipia West", "Uasonarock", "Celina Amaniman Adengo", "Laikipia West", "KAICHAKUNI"],
  ["Laikipia West", "Uasonarock", "James Lolukio Loitang\"ole", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "Uasonarock", "Nicholas Njuguna Kago", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "Uasonarock", "ESTHER A. NARO", "Laikipia West", "KAICHAKUNI"],
  ["Laikipia West", "Uasonarock", "CORRISON NDIRANGU", "Laikipia West", "UASONAROCK B"],
  ["Laikipia West", "TOWN  A", "Eliaph Wambugu Muriithi", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "Purity Mumbi Wamuyu", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "Phoebe Kirigo Nderitu", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "Samuel Kamau Ngugi", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "Tabitha Wanjira King'ori", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "David Kiruri Ndonga", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "Catherine Wambui Gichuka", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "Mary Wambui Kiong'e", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "CECILIA MUCHIRI", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "NORAH ADHIAMBO", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN A", "BETH WANGECHI", "Laikipia West", "Nyahururu Juakali"],
  ["Laikipia West", " TOWN B", "Josphat Wahome Karemi", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", "TOWN B", "Boniface Gatiki ", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", "TOWN B", "Mary Muthoni Muchemi", "Laikipia West", "TOWN B ( Cosite)"],
  ["Laikipia West", " TOWN B", "Sabina Gichuki Gathoni", "Laikipia West", "TOWN C (Cosite)"],
  ["Laikipia West", " TOWN B", "David Wanderi Mwaura", "Laikipia West", "TOWN C (Cosite)"],
  ["Laikipia West", " TOWN B", "Pauline Koech Chepkorir", "Laikipia West", "TOWN B Coste"],
  ["Laikipia West", " TOWN B", "Simon Gachanja", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", " TOWN B", "ALEXANDER MACHARIA ", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", " TOWN B", "MARY NGUGI ", "Laikipia West", "TOWN C (Cosite)"],
  ["Laikipia West", " TOWN B", "Tabitha Waceke Mani", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", " TOWN B", "MARGARET WANGECI ", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", " TOWN B", "DAVID GATHURI ", "Laikipia West", "TOWN C ( Cosite)"],
  ["Laikipia West", " TOWN B", "Caroline Wachera Githinji", "Laikipia West", "TOWN B ( Cosite)"],
  ["Laikipia West", "KARAND\\ M|", "Monicah Njoki Nderitu", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Monicah Wanjiru Ndirangu", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "David Maina Kamau", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "Angelus Mwihuri Gichuki", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Milkah Wangui Wambugu", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "Eunice Wanjiru Wangombe", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "Zablon Ogonyo Osiago", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Ann Muthoni Wanjohi", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Tabitha Mugure Muturi", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "Rose Njeri Karengo", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Phillip Muriithi Gathigia", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Susan Loching’ing Lobuu", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "Phillip Kamau Muchai", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND\\ M|", "Loise Wangechi Nyaguthii", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", "KARAND\\ M|", "Beatrice Njeri Njoroge", "Laikipia West", "MUTHENGERA A"],
  ["Laikipia West", "KARAND/ MUTHENGERA", "Alice Nduta Njuguna", "Laikipia West", "MUTHENGERA B"],
  ["Laikipia West", " NGARUA", "Paul Barno Kimtai", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Francis Kibet Ngetich", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Mercy Njeri Wahome", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Gladys Tarus Chebor", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Jacqueline Wanjiku Wangechi", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Samuel  Cheruiyot Kipruto ", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Peter Njenga Wairegi", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Samuel Mbaruku Kariuki", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Mary Chepchumba Katam", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Alice Njambi Kibiki", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Leah Njoki Ndiangui", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Christine Jebet Kiptoo", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Mary  ChelangatYator ", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Vivian Jerotich chirchir", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Martha Wambui Gathumbi", "Laikipia West", "THIGIO"],
  ["Laikipia West", " NGARUA", "Dorcas Chebet Kosgei", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Sheila Jelagat Kipsire", "Laikipia West", "THIGIO"],
  ["Laikipia West", " NGARUA", "Samuel Kimeli Kangogo", "Laikipia West", "THIGIO"],
  ["Laikipia West", " NGARUA", "Ann Muthoni Nganga", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Julius Waithaka Mureithi", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Mary Wanjugu Njogu", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Alice Njeri Karanja", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Salina Chelimo Arusei", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Esther Wangui Kariuki", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Christos Murigi Njuguna", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "James Maina Wangui", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Ruth Wambui Chege", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Joseph Gachure Thairu", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Henry Kipkorir Kenduiyo", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Ann Mumbi Muriuki", "Laikipia West", "ngarua"],
  ["Laikipia West", " NGARUA", "Grace Chemeli Kipsoi", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", "Julius Kipkemoi Kiptarus", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Nancy Chepchirchir Kibinai", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Beatrice Wangui  Thiga", "Laikipia West", "NGARUA B"],
  ["Laikipia West", " NGARUA", " Kariuki M. Mwangi", "Laikipia West", "SERIA"],
  ["Laikipia West", " NGARUA", "Monicah Wangui Wachira", "Laikipia West", "THIGIO"],
  ["Laikipia West", " NGARUA", "James Kiptoo Koringo", "Laikipia West", "THIGIO"],
  ["Laikipia West", " NGARUA", "NancY Jepchupo Tarus", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Benson Kiptanui Kibor", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Jane Wambui Irungu", "Laikipia West", "GATIRIMA"],
  ["Laikipia West", " NGARUA", "Samuel  Gitonga Muthara", "Laikipia West", "THIGIO"],
  ["Laikipia West", "OLJABET", "David Gitahi Gachoya", "Laikipia West", "OLJABET B"],
  ["Laikipia West", "OLJABET", "Joseph Mutahi Wamai", "Laikipia West", "oljabet"],
  ["Laikipia West", "OLJABET", "James Ngatu Kamau", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "Joseph Gichuhi Mwangi", "Laikipia West", "oljabet"],
  ["Laikipia West", "OLJABET", "Kezia Nyambura Maina", "Laikipia West", "oljabet"],
  ["Laikipia West", "OLJABET", "Maureen. Wanjiku Njenga", "Laikipia West", "OLJABET B"],
  ["Laikipia West", "OLJABET", "Eunice Cheptoo Chepchok", "Laikipia West", "OLJABET B"],
  ["Laikipia West", "OLJABET", "Caren Keziah mbaizi Luvisia", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "Regina Wanja Munyiri", "Laikipia West", "OLJABET B"],
  ["Laikipia West", "OLJABET", "Rahab Wangari Kamau", "Laikipia West", "OLJABET"],
  ["Laikipia West", "OLJABET", "Grace Wanjuhi Wakaba", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "Emily Njoki Wachera", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "Prisca Cheptum Kipkoskei", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "JANET WANGUI", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "WINNIE MUTHONI", "Laikipia West", "OLJABET B"],
  ["Laikipia West", "OLJABET", "MARY WANJIKU KIRUNDE", "Laikipia West", "OLJABET B"],
  ["Laikipia West", "OLJABET", "VIRGINIA WANGARI", "Laikipia West", "oljabet"],
  ["Laikipia West", "OLJABET", "REBECCA NYOKABI WAGURA", "Laikipia West", "oljabet"],
  ["Laikipia West", "OLJABET", "MERCY WAJIRA MUNUHE", "Laikipia West", "oljabet"],
  ["Laikipia West", "OLJABET", "WINFRED WANJIRU KAMORE", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "OLJABET", "CHRISTINE CHELANGAT KOIMA", "Laikipia West", "OLJABET C"],
  ["Laikipia West", "SIRONI", "Esther Wangui Kimani", "Laikipia West", "SIRONI B"],
  ["Laikipia West", "SIRONI", "RUTH WANJIKU KIHUMBA", "Laikipia West", "SIRONI B"],
  ["Laikipia West", "SIRONI", "LUCY MUGURE KABIBIA", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "ANN WANJIRU WAMBUGU", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "JESSE KAHIGA MATHENGE", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "TABITHA WANJIRU KABUGI", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "ELISHIPA WAITHIRA WAMBUGU", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "HANNAH WAIRIMU KARIUKI", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "MARGARET NYAMBURA MUGAMBI", "Laikipia West", "SIRONI B"],
  ["Laikipia West", "SIRONI", "Joyce Wathira Muiruri", "Laikipia West", "SIRONI B"],
  ["Laikipia West", "SIRONI", "Tabitha Nyambura Mbuthia", "Laikipia West", "SIRONI B"],
  ["Laikipia West", "SIRONI", "Jane Njeri Ngugi", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "Ann Wambui Karanja", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "Margaret Wawitima Ndirangu ", "Laikipia West", "Sironi"],
  ["Laikipia West", "SIRONI", "Francis Kariuki Machomba", "Laikipia West", "SIRONI B"],
  ["Laikipia West", "RUMURUTI ", "Miykelina Namoe Emathe", "Laikipia West", "RUMURUTI C"],
  ["Laikipia West", "RUMURUTI ", "Scola Jerotic", "Laikipia West", "RUMURUTI B"],
  ["Laikipia West", "RUMURUTI ", "Purity Wanjiku Kariuki", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "Grace Kambua Kimatu", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Zainabu  Muhamed", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Moses Macharia", "Laikipia West", "RUMURUTI B"],
  ["Laikipia West", "RUMURUTI ", "Catherine Njoki Mathenge", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "Francisca Ida Lenaitorono", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "Peris Wamuyu Gathogo", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Jane Wambui Marii", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Marther Piroris", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Jane Wachuka Njunjiri", "Laikipia West", "RUMURUTI C"],
  ["Laikipia West", "RUMURUTI ", "Grace Wanjiru Ngendi", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Petronilla Muthoni Wanjiku", "Laikipia West", "RUMURUTI B"],
  ["Laikipia West", "RUMURUTI ", "Geoffrey Mwangi Kiuma", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "Hellen Wamuyu Munuhe", "Laikipia West", "RUMURUTI B"],
  ["Laikipia West", "RUMURUTI ", "Joyce Wambui Muchiri", "Laikipia West", "RUMURUTI C"],
  ["Laikipia West", "RUMURUTI ", "Mary Cheptoo Ruto", "Laikipia West", "RUMURUTI C"],
  ["Laikipia West", "RUMURUTI ", "Joseph Lopuchingiro Emuria", "Laikipia West", "RUMURUTI C"],
  ["Laikipia West", "RUMURUTI ", "Alice  Cheree", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "Josca Magak Aoko", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "JANE GATHIGIA WAINAINA", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "FELISTA WAMBUI", "Laikipia West", "RUMURUTI D"],
  ["Laikipia West", "RUMURUTI ", "Rose Sammy Kilukie", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "RUMURUTI ", "PETER NAIMADO", "Laikipia West", "RUMURUTI B"],
  ["Laikipia West", "RUMURUTI ", "JOHN SUPEYO", "Laikipia West", "RUMURUTI B"],
  ["Laikipia West", "RUMURUTI ", "Esther  Wagaki Mwai", "Laikipia West", "RUMURUTI"],
  ["Laikipia West", "MUTAMAIYU", "Rahab Wanjiru Kimani", "Laikipia West", "NDURUMO"],
  ["Laikipia West", "MUTAMAIYU", "Charles Maina Koinange", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "MUTAMAIYU", "Alice Nyambura Muchangi", "Laikipia West", "NDURUMO"],
  ["Laikipia West", "MUTAMAIYU", "Jane Wangeci Kiragu", "Laikipia West", "NDURUMO"],
  ["Laikipia West", "MUTAMAIYU", "Mary Wambui Kuria", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "MUTAMAIYU", "Ann Wangui", "Laikipia West", "NDURUMO"],
  ["Laikipia West", "MUTAMAIYU", "Christoper Loloe Ewoi", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "MUTAMAIYU", "SHeilia Chelangat Kipkemei", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "MUTAMAIYU", "Samwel Rotiakwe Ekilab", "Laikipia West", "NDURUMO"],
  ["Laikipia West", "MUTAMAIYU", "Maria Watiri", "Laikipia West", "NDURUMO"],
  ["Laikipia West", "MUTAMAIYU", "Ann Akai", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "MUTAMAIYU", "Mary Wairimu Mbugua", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "MUTAMAIYU", "Philip Ruto", "Laikipia West", "MUTAMAnYU"],
  ["Laikipia West", "THOME", "Joshua Maingi Karanja", "Laikipia West", "THOME C"],
  ["Laikipia West", "THOME", "Barnabas Ekaran Eleman", "Laikipia West", "THOME C"],
  ["Laikipia West", "THOME", "Florence  Lima", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "Hassan Dahir Abdi", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "Peter Edung Naiyajalan", "Laikipia West", "THOME"],
  ["Laikipia West", "THOME", "Patrick Muthee Nganga", "Laikipia West", "THOME C"],
  ["Laikipia West", "THOME", "Damaris Wairimu Lomingarani", "Laikipia West", "THOME"],
  ["Laikipia West", "THOME", "Jackson Clause Lepartango", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Grace Muthoni Muthanga", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Veronica Naivesti Abarbar", "Laikipia West", "THOME"],
  ["Laikipia West", "THOME", "Rebecca Alipan Elyapan", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Simon  Kamshon", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "Richard Kihumba Ngechu", "Laikipia West", "THOME"],
  ["Laikipia West", "THOME", "Harun Mwangi Mundia", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "Julius Kasuku Lomingala", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "James Njuguna Mbugua", "Laikipia West", "THOME C"],
  ["Laikipia West", "THOME", "Alice Akai Ekwom", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "James Awechi Eyanae", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Francis Lemoroko", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Reuben Lokurum", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Jane Pakisi Lesaja", "Laikipia West", "MATHIRA"],
  ["Laikipia West", "THOME", "Moses Meluya Lesabaine", "Laikipia West", "THOME B"],
  ["Laikipia West", "THOME", "Daniel Kibwambok Chepkwony", "Laikipia West", "THOME"],
  ["Laikipia West", "THOME", "Lucy Lutoko", "Laikipia West", "THOME"],
  ["Laikipia West", "THOME", "Scholor  Ijike", "Laikipia West", "THOME"],
  ["Laikipia West", "PESI", "Hannah Wanjugu Githui", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "James Mwangi Ndiritu", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "JAMES EKURU MITIKA", "Laikipia West", "MUTARA"],
  ["Laikipia West", "PESI", "Beatrice  WAIRIMU Kamunya", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "John Ndiithi Njagu", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "David Thiga Watoro", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "Lucy Wanjiku Wanjiru", "Laikipia West", "MUTARA"],
  ["Laikipia West", "PESI", "Mary Mumbi Ngari", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "John Ng'ang'a Nderitu", "Laikipia West", "Kiamariga"],
  ["Laikipia West", "PESI", "Johanna Githinji Kigoro", "Laikipia West", "MUTARA"],
  ["Laikipia West", "PESI", "ELIZABETH NAPEYOK MURU", "Laikipia West", "MUTARA"],
  ["Laikipia West", "PESI", "JOSPHAT EKWAM LOSIRIM", "Laikipia West", "MUTARA"],
  ["Laikipia West", "PESI", "Mercy Nalibany", "Laikipia West", "MUTARA"],
  ["Laikipia West", "PESI", "Gilbert Githinji", "Laikipia West", "MUTARA"],
  ["Laikipia West", "KABATI", "David Gatimu Macharia", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "Joseph Gathara Ndengwa", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "Ann Wangari Ngunjiri", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "Wilson Kamau Maina", "Laikipia West", "KABATI"],
  ["Laikipia West", "KABATI", "Elizabeth Wangui Maina", "Laikipia West", "KABATI"],
  ["Laikipia West", "KABATI", "Susan Chelalang Tanui", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "Susan Chepkoech Kiptanui", "Laikipia West", "KABATI"],
  ["Laikipia West", "KABATI", "Joseph Maina Macharia", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "SAMUEL NJEHIA MWANIKI", "Laikipia West", "KABATI"],
  ["Laikipia West", "KABATI", "BEATRICE WANJIKU MATHENGE", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "MARY WAMBUI WANJIKU", "Laikipia West", "KABATI"],
  ["Laikipia West", "KABATI", "ALICE WAMBUI THARARI", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "LUCIA MUTHONI KAGURU", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "JANE WAMUCII KAMUNGE", "Laikipia West", "KABATI B"],
  ["Laikipia West", "KABATI", "BETSY JEBIWOT YATICH", "Laikipia West", "KABATI"],
  ["Laikipia West", "KABATI", "MIRIAM WANGUI MUTURI", "Laikipia West", "KABATI"],
  ["Laikipia West", "SIPILI", "Daniel Mwangi Kahiga", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Jedidah Wanjiku Njoroge", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Miriam Mwihaki Ndirangu", "Laikipia West", "SIPILI"],
  ["Laikipia West", "SIPILI", "Lucy Njeri Njenga", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Lucy Gathigia Maina", "Laikipia West", "SIPILI"],
  ["Laikipia West", "SIPILI", "Maryanne Wanjiku Wamuti", "Laikipia West", "SIPILI B"],
  ["Laikipia West", "SIPILI", "Dorcas Wambui Ngaruiya", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Samuel Macharia David", "Laikipia West", "SIPILI B"],
  ["Laikipia West", "SIPILI", "Racheal Wairimu Mwangi", "Laikipia West", "SIPILI"],
  ["Laikipia West", "SIPILI", "Leah Wamuyu Kamanga", "Laikipia West", "SIPILI B"],
  ["Laikipia West", "SIPILI", "Jane Njeri Ndungu", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Elizabeth Wanjiru Wainaina", "Laikipia West", "SIPILI B"],
  ["Laikipia West", "SIPILI", "Lucy Kabura Ndegwa", "Laikipia West", "SIPILI"],
  ["Laikipia West", "SIPILI", "Monicah Njeri Njuguna", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Suleiman Wachira Warui", "Laikipia West", "SIPILI"],
  ["Laikipia West", "SIPILI", "Jonna Mbuthi Kamau", "Laikipia West", "SIPILI"],
  ["Laikipia West", "SIPILI", "Hezron Ngugi", "Laikipia West", "SIPILI C"],
  ["Laikipia West", "SIPILI", "Philomena Wamaitha Muraguri", "Laikipia West", "SIPILI B"],
  ["Laikipia West", "OLMORAN", "KENNETH KIPKEMBOI KEBENEI", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "SIMON MWANGI KIRURI", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "MOSES  NJUGUNA", "Laikipia West", "OLMORAN B"],
  ["Laikipia West", "OLMORAN", "JOSEPH AWU ELELE", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "LUCY NJERI MWANGI", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "SERAH CHELIMO KIPLANGAT", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "JOHN NGETHE KUNGU", "Laikipia West", "OLMORAN B"],
  ["Laikipia West", "OLMORAN", "SAMUEL MWANGI NJUGUNA", "Laikipia West", "OLMORAN B"],
  ["Laikipia West", "OLMORAN", "VERONICA NJERI NDUNGU", "Laikipia West", "OLMORAN B"],
  ["Laikipia West", "OLMORAN", "MARY WANGUI NGARI", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "JAMES ACHOTO EROT", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "MARY AKAI NAKWAI", "Laikipia West", "OLMORAN B"],
  ["Laikipia West", "OLMORAN", "MARGARET AWOI ESEKON", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "HANNAH NYAMBURA KIMANI", "Laikipia West", "OLMORAN"],
  ["Laikipia West", "OLMORAN", "SAMUEL WAMUTU MWANGI", "Laikipia West", "OLMORAN B"],
  ["laikipia west", "GITHIMA", "Margaret  Wanjiru Nyambura", "Laikipia West", "GITHIMA"],
  ["laikipia west", "GITHIMA", "Joseph kamau ", "Laikipia West", "GITHIMA B"],
  ["laikipia west", "GITHIMA", "Margret muthoni ", "Laikipia West", "GITHIMA"],
  ["laikipia west", "GITHIMA", "James thuo ", "Laikipia West", "GITHIMA"],
  ["laikipia west", "GITHIMA", "Eunice nyambura ", "Laikipia West", "GITHIMA B"],
  ["laikipia west", "GITHIMA", "Phylis mumbi kamau", "Laikipia West", "GITHIMA"],
  ["laikipia west", "GITHIMA", "Daniel warugongo ", "Laikipia West", "GITHIMA B"],
  ["laikipia west", "GITHIMA", "Joseph Githuo Kinyua", "Laikipia West", "GITHIMA B"],
  ["laikipia west", "GITHIMA", "Paul Kamau Mwangi", "Laikipia West", "GITHIMA B"],
  ["laikipia west", "KAITI", "Frida Muthoni", "Laikipia West", "KAITI B"],
  ["laikipia west", "KAITI", "Peter Kariuki Thuku", "Laikipia West", "KAITI"],
  ["laikipia west", "KAITI", "Joyce Ndasi Muttio", "Laikipia West", "KAITI C"],
  ["laikipia west", "KAITI", "Lucy Wanjiku Wang'ondu", "Laikipia West", "KAITI C"],
  ["laikipia west", "KAITI", "Winfred Wanjiku Mbiriri", "Laikipia West", "KAITI C"],
  ["laikipia west", "KAITI", "Benadetah Ngina Karanja", "Laikipia West", "KAITI C"],
  ["laikipia west", "KAITI", "Jecinta Wamahiga Wagura", "Laikipia West", "KAITI B"],
  ["laikipia west", "KAITI", "John Ndirangu Gitonga", "Laikipia West", "KAITI"],
  ["laikipia west", "KAITI", "Florence Wanjiru Kaithi", "Laikipia West", "KAITI"],
  ["laikipia west", "KAITI", "Lucas Kiburio Ngatia", "Laikipia West", "KAITI"],
  ["laikipia west", "KAITI", "Nancy  Nyambura", "Laikipia West", "KAITI B"],
  ["laikipia west", "KAITI", "Peter Kamau Kariuki", "Laikipia West", "KAITI"],
  ["laikipia west", "KAITI", "Anastasia Njeri Mwaura", "Laikipia West", "KAITI B"],
  ["laikipia west", "KAITI", "Simon Kibet Sambu", "Laikipia West", "KAITI B"],
  ["laikipia west", "KAITI", "Peter Gathitu", "Laikipia West", "KAITI"],
  ["laikipia west", "KAITI", "Mirriam Nyaguthii Wahome", "Laikipia West", "KAITI C"]
];
