name: Deploy

on:
  # workflow_run:
  #   workflows: [Docker build and publish]
  #   types:
  #     - completed
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: install oathtool
        run: sudo apt-get install -y oathtool jq

      - name: Authenticate to STS
        run: |
          mfa_serial="arn:aws:iam::${{vars.AWS_ACCOUNT_NUMBER}}:mfa/gh-action"
          mfa_code=$(oathtool -b --totp ${{secrets.MFA_KEY}})

          STS=$(aws sts get-session-token --region "eu-west-2" --serial-number "$mfa_serial" --token-code "$mfa_code")
          aws configure set aws_access_key_id $(echo "$STS" | jq -r '.Credentials.AccessKeyId') --profile "${{vars.AWS_USER}}"
          aws configure set aws_secret_access_key $(echo "$STS" | jq -r '.Credentials.SecretAccessKey') --profile "${{vars.AWS_USER}}"
          aws configure set aws_session_token $(echo "$STS" | jq -r '.Credentials.SessionToken') --profile "${{vars.AWS_USER}}"

      - name: Assume role
        run: |
          EKS=$(aws sts assume-role --region "eu-west-2" --role-arn "arn:aws:iam::${{vars.AWS_ACCOUNT_NUMBER}}:role/eks-${{vars.AWS_USER}}" --role-session-name="${{vars.AWS_USER}}-ghaction" --profile "${{vars.AWS_USER}}")
          aws configure set aws_access_key_id $(echo "$EKS" | jq -r '.Credentials.AccessKeyId') --profile "${{vars.AWS_USER}}"
          aws configure set aws_secret_access_key $(echo "$EKS" | jq -r '.Credentials.SecretAccessKey') --profile "${{vars.AWS_USER}}"
          aws configure set aws_session_token $(echo "$EKS" | jq -r '.Credentials.SessionToken') --profile "${{vars.AWS_USER}}"

      - uses: actions/checkout@v2

      - name: Helm upgrade
        run: |
          aws eks update-kubeconfig --name prod-cht-eks --region "eu-west-2"
          helm repo add medic https://docs.communityhealthtoolkit.org/helm-charts
          helm upgrade --namespace users-chis-prod --values scripts/deploy/values/users-chis-civ.yaml users-chis-civ medic/cht-user-management
