name: Tests in CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm test
