name: Run Build and Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Build and Tests
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm test
