name: Run Build and Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Build and Tests
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run check
    - run: npm test
    - run: npm run build
